macro(detect_compiler)
    if("${CMAKE_C_COMPILER_ID}" STREQUAL "GNU")
        message(STATUS "Detected gcc compiler")
        set(ATLAS_COMPILER "gcc")
    elseif("${CMAKE_C_COMPILER_ID}" STREQUAL "Clang")
        message(STATUS "Detected clang compiler")
        set(ATLAS_COMPILER "clang")
    elseif("${CMAKE_C_COMPILER_ID}" STREQUAL "MSVC")
        message(STATUS "Detected msvc compiler")
        set(ATLAS_COMPILER "msvc")
    else()
        message(STATUS "Unsupported compiler: '${CMAKE_C_COMPILER_ID}'")
    endif()
endmacro(detect_compiler)

macro(set_gcc_defines)
    add_definitions(-DATLAS_GCC)
endmacro(set_gcc_defines)

macro(set_clang_defines)
    add_definitions(-DATLAS_CLANG)
endmacro(set_clang_defines)

macro(set_msvc_defines)
    add_definitions(-DATLAS_MSVC)
endmacro(set_msvc_defines)

macro(set_compiler_defines)
    if(${ATLAS_COMPILER} STREQUAL "gcc")
        set_gcc_defines()
    elseif(${ATLAS_COMPILER} STREQUAL "clang")
        set_clang_defines()
    elseif(${ATLAS_COMPILER} STREQUAL "msvc")
        set_msvc_defines()
    else()
        message(FATAL_ERROR "Unknown compiler")
    endif()
endmacro(set_compiler_defines)

macro(set_gcc_compile_options)
    message(STATUS "Configuring gcc compile options")

    add_compile_options(-Wall -Wextra -Werror -Wshadow)
    add_compile_options(-Wno-override-init -Wno-missing-field-initializers -Wno-type-limits -Wno-implicit-fallthrough -Wno-clobbered)

    add_compile_options(-g -fno-omit-frame-pointer)
endmacro(set_gcc_compile_options)

macro(set_clang_compile_options)
    message(STATUS "Configuring clang compile options")

    add_compile_options(-Wall -Wextra -Werror -Wshadow -Wgnu-empty-initializer)
    add_compile_options(-Wno-initializer-overrides)

    add_compile_options(-g -fno-omit-frame-pointer)

    if(${ATLAS_PLATFORM} STREQUAL "linux")
        set(SANITIZERS "address,alignment,builtin,bounds,integer-divide-by-zero")

        message(STATUS "Configuring clang sanitizers: ${SANITIZERS}")
        add_compile_options(-fsanitize=${SANITIZERS})
        add_link_options(-fsanitize=${SANITIZERS})
    elseif(${ATLAS_PLATFORM} STREQUAL "win32" OR CMAKE_SYSTEM_NAME STREQUAL "Windows")
        set(SANITIZERS "address")

        message(STATUS "Configuring clang sanitizers for Windows: ${SANITIZERS}")
        add_compile_options(-fsanitize=${SANITIZERS})
        add_link_options(-fsanitize=${SANITIZERS})
        add_compile_options(-fno-omit-frame-pointer)
        add_link_options(-fno-omit-frame-pointer)
    endif()
endmacro(set_clang_compile_options)

macro(set_msvc_compile_options)
    message(STATUS "Configuring msvc compile options")

    add_compile_options(/TC /std:c11)
    add_compile_options(/utf-8)
    add_compile_options(/W4 /WX /wd4127 /wd5105 /wd4200 /wd4244 /wd4201 /wd4210 /wd4701)
    add_compile_options(/wd4189)
    add_compile_options(/Zc:preprocessor)
    add_compile_options(/FS /Zi)

endmacro(set_msvc_compile_options)

macro(set_compile_options)
    set(CMAKE_C_FLAGS_DEBUG "")
    set(CMAKE_C_FLAGS_RELEASE "")
    set(CMAKE_C_FLAGS_RELWITHDEBINFO "")
    set(CMAKE_C_FLAGS_MINSIZEREL "")

    if (${ATLAS_PLATFORM} STREQUAL "linux")
        message(STATUS "Configuring pthread threading")
        add_compile_options(-pthread)
        add_link_options(-pthread)
    endif()

    if (${ATLAS_COMPILER} STREQUAL "gcc")
        set_gcc_compile_options()
    elseif (${ATLAS_COMPILER} STREQUAL "clang")
        set_clang_compile_options()
    elseif (${ATLAS_COMPILER} STREQUAL "msvc")
        set_msvc_compile_options()
    else()
        message(FATAL_ERROR "Unknown compiler")
    endif()
endmacro(set_compile_options)
